# `sheldon` configuration file
# ----------------------------
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# more colors
[plugins.base16]
github = "chriskempson/base16-shell"

# fancy prompt
[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

# command highlighting
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
